### ISSUE TITLE
[1.12.2] Wrong amplifier values?

### ISSUE THREAD

**Issue by xJon** [Christofmeg/IC2C-UU-Matter#4]
Using `1.1.1`:
![image](https://user-images.githubusercontent.com/8945347/229327602-b0170e88-0b62-4d18-bd5c-f573204838c3.png)
(Metal scrap value renders correctly on the other page as `100,000`)

**Comment by Christofmeg** [comment]
@xJon 
Can you export a copy of the pack you're using, so I can reproduce the issue?
- Configs, Mods and Resourcepacks

**Comment by xJon** [comment]
@Christofmeg Yes, simply the latest version (`1.2.0`) of [Tekkit 2](https://www.technicpack.net/modpack/tekkit-2). You can download it using Technic/Prism/MultiMC launchers

**Comment by Christofmeg** [comment]
@xJon 
Thank you for reporting this issue! I've fixed the problem, and updates should available on CurseForge, GitHub and Modrinth shortly :)
